import type { Tree, Flashcard } from "./App"

export const mockTrees: Tree[] = [
  {
    id: 1,
    name: "Introduction to React",
    hash: "abc123",
    userId: "user1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    name: "JavaScript Fundamentals",
    hash: "def456",
    userId: "user1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    name: "TypeScript Basics",
    hash: "ghi789",
    userId: "user1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const mockFlashcards: Flashcard[] = [
  {
    id: 1,
    treeId: 1,
    front: "What is React?",
    back: "React is a JavaScript library for building user interfaces, particularly web applications.",
    interval: 1,
    easeFactor: 2.5,
    nextReview: new Date(),
    name: "React Definition",
    nodeId: 1,
    userId: "user1",
  },
  {
    id: 2,
    treeId: 1,
    front: "What are React components?",
    back: "React components are reusable pieces of code that return JSX to describe what should appear on the screen.",
    interval: 1,
    easeFactor: 2.5,
    nextReview: new Date(),
    name: "React Components",
    nodeId: 2,
    userId: "user1",
  },
  {
    id: 3,
    treeId: 2,
    front: "What is closure in JavaScript?",
    back: "A closure is a function that has access to variables in its outer (enclosing) lexical scope, even after the outer function has returned.",
    interval: 1,
    easeFactor: 2.5,
    nextReview: new Date(),
    name: "JavaScript Closures",
    nodeId: 3,
    userId: "user1",
  },
  {
    id: 4,
    treeId: 2,
    front: "What is the difference between let, const, and var?",
    back: "var is function-scoped and can be redeclared. let is block-scoped and can be reassigned. const is block-scoped and cannot be reassigned.",
    interval: 1,
    easeFactor: 2.5,
    nextReview: new Date(),
    name: "Variable Declarations",
    nodeId: 4,
    userId: "user1",
  },
  {
    id: 5,
    treeId: 3,
    front: "What is TypeScript?",
    back: "TypeScript is a superset of JavaScript that adds static type definitions, making code more maintainable and less error-prone.",
    interval: 1,
    easeFactor: 2.5,
    nextReview: new Date(),
    name: "TypeScript Definition",
    nodeId: 5,
    userId: "user1",
  },
]

